### PR TITLE
docs: add two more projects to readme

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
how many projects total do you think we should have in the readme? because i feel like the list can at some point get too long

**Comment by benmccann** [comment]
Yeah. I think like 10-12 is good. I might not make it much longer than this

**Comment by ghiscoding** [comment]
I was thinking the same as well, `@sanity/import` has only 1 star, does it really deserve to be part of this list? Personally, I would think that only the biggest project, with high download rate, should be referenced. 

Side note, I have migrated [Lerna-Lite](https://github.com/lerna-lite/lerna-lite) to `tinyglobby` over a week ago but only released it today 🚀 I'm trying to get couple weeks between releases in case something goes wrong 😄 

Cheers and thanks for the lib

**Comment by benmccann** [comment]
`@sanity/import` has 125k weekly downloads. The list is sorted by downloads. 

However, I have replaced it with another project that just switched over and has 10x as many downloads. The two libraries added by this PR are now the second and third most downloaded consumers of this package

**Review by SuperchupuDev — APPROVED** [review]
thanks :-)

**Pull request merged**
