### PR TITLE
initial exclude optimizer implementation

### LINKED ISSUE #46: Potentially the biggest performance improvement that can be done
I'm not even sure how to approach the problem, but implementing this means that all of the weird patterns that currently avoid all optimizations would be really optimized along with literally everything else.

By default, `fdir` crawls all subdirectories and files of a root, which can result in extra processing work that's not necessary, harming performance. `tinyglobby` tries to apply some optimizations by inferring a common root.

`fdir` exposes a `exclude` function that can be used to exclude directories from crawling. It's being currently used on the `ignore` patterns to... not crawl those ignored patterns?

What if, we took the matching patterns (basically the patterns that aren't meant to be ignored), we did some weird transformations to them, and used them in the `exclude` matcher?

For example, let's say we have the following usage:

```js
import { glob } from 'tinyglobby';

await glob(['src/files/index.ts', 'scripts/*.ts']);
```

with the following file structure:
```
- node_modules
  ^big
- plugins
  - myPlugins
    | plugin.ts
- scripts
  - utils
    | index.ts
  | deploy.ts
  | run.ts
- src
  - files
    | index.ts
  - other
    | index.ts
```

Basically, we need a picomatch matcher that returns `true` for every directory that we don't want to crawl, in this case `node_modules`, `plugins`, `scripts/utils`, and `src/other`. This could be implemented with the following picomatch usage:
```js
import picomatch from 'picomatch';

const exclude = picomatch('**/*', {
  ignore: ['src/files', 'scripts/*/**']
});
```

Great! It now only crawls the directories needed (hopefully, I haven't checked). Now the question is how to implement something that converts `['src/files/index.ts', 'scripts/*.ts'` into `['src/files', 'scripts/*/**']`, which is the whole point of this issue. If we figure it out, `tinyglobby` should be nearly as fast as possible.

Some notes:
- Whatever thing is implemented needs to take into account how `<pattern>/**` patterns work. It not only matches subdirectories of `<pattern>`, but it also matches `<pattern>` itself. this is why the second processed pattern in the example isn't `scripts/**`, as that would match `scripts` making `fdir` not crawl it.
- Ideally this processing should happen in the `normalizePattern` function, so that we don't need to loop through the patterns extra times.

### PR DESCRIPTION
**Pull request by xiboon**
Closes #46 yay....!!!!

### CODE REVIEW

**Comment by robertsLando** [comment]
I would also suggest to add a test that does some performance check and compare results with globby

**Comment by SuperchupuDev** [comment]
for anyone interested in helping, this PR makes vite tests fail, but we are struggling to debug it due to the message produced (and a lack of time). you can see the ci run on my test fork https://github.com/SuperchupuDev/vite

**Comment by xuanduc987** [comment]
After some debugging, seems like the problem was lone double star `**` pattern, I tried to fix it with xiboon/tinyglobby#1

**Comment by robertsLando** [comment]
@SuperchupuDev could you merge @xuanduc987 changes and retry vite tests?

**Comment by SuperchupuDev** [comment]
> After some debugging, seems like the problematic one was lone double star `**` pattern, I tried to fix it with [xiboon#1](https://github.com/xiboon/tinyglobby/pull/1)

merged, thanks :)
will rerun vite's tests

**Comment by SuperchupuDev** [comment]
vite tests pass :O

**Comment by SuperchupuDev** [comment]
testing in some more repos, 3 tests from `@yao-pkg/pkg` are failing, again with no clear error message 🫠 https://github.com/yao-pkg/pkg/actions/runs/12068434516/job/33653545386?pr=121

**Comment by xuanduc987** [comment]
@SuperchupuDev Isn't the reason for the failing tests is this?
https://github.com/yao-pkg/pkg/pull/121#issuecomment-2460221222
Revert the change to `collect` function would make it green I think.

**Comment by SuperchupuDev** [comment]
oh, right, thought i had reverted that... my bad

**Review by SuperchupuDev — APPROVED** [review]
there are some improvements that can be done (and i'll try to do before a new release), but it's good as an initial implementation. thanks everyone for the help! :)

**Pull request merged**
